Add test to increase coverage
digitalbazaar/bedrock-meter-usage-reporter pull request #7
Opened 2022-01-04 14:50 UTC by JSAssassin

Increases coverage to 85.95%

2022-01-04 15:00 UTC, JSAssassin commented on test/mocha/10-meters.js
> +  it.skip('should throw error if meter "serviceId" does not match client id',
This test is skipped for now since as far as I can tell, we’ll never be able to reach this error - https://github.com/digitalbazaar/bedrock-meter-usage-reporter/blob/main/lib/meters.js#L495-L503. When the "service id" and "client id" are not matching then it fails before getting to that error on this line https://github.com/digitalbazaar/bedrock-meter-usage-reporter/blob/main/lib/meters.js#L491 with an authorization error.

2022-01-10 23:46 UTC, dlongley requested changes

2022-01-10 23:46 UTC, dlongley commented on lib/meters.js
> +  }
```suggestion
  }

```

2022-01-10 23:46 UTC, dlongley commented on lib/meters.js
>    // add unreported operations from the meter to the usage
```suggestion
  // add unreported operations from the meter to the usage
  /* Note: It is safe to add the unreported operations from the
  previously retrieved record even though it was retrieved
  prior to locking the record. This is because proper usage
  of the lock API causes the lock to fail if the record has
  changed. */
```

2022-01-10 23:46 UTC, dlongley commented on test/helpers.js
> + * Copyright (c) 2021 Digital Bazaar, Inc. All rights reserved.
```suggestion
 * Copyright (c) 2021-2022 Digital Bazaar, Inc. All rights reserved.
```

2022-01-10 23:46 UTC, dlongley commented on test/mocha/10-meters.js
>   * Copyright (c) 2021 Digital Bazaar, Inc. All rights reserved.
```suggestion
 * Copyright (c) 2021-2022 Digital Bazaar, Inc. All rights reserved.
```

2022-01-10 23:47 UTC, dlongley commented on test/mocha/10-meters.js
> +  it.skip('should throw error if meter "serviceId" does not match client id',
It only fails before getting to that line because the server is properly implemented. We need to mock a bad response so that we're handling the case of a bad server.

2022-01-11 21:38 UTC, dlongley commented on test/mocha/10-meters.js
> +  it.skip('should throw error if meter "serviceId" does not match client id',
Let's punt solving this one to a later time. Please leave a comment above the `it.skip` that says it's skipped until we add a mock invalid server response.

2022-01-11 21:38 UTC, dlongley approved these changes

2022-01-11 21:41 UTC, merged