Fix skipped test.
digitalbazaar/bedrock-meter-usage-reporter pull request #8
Opened 2022-01-11 22:30 UTC by JSAssassin

2022-01-12 15:31 UTC, dlongley requested changes

2022-01-12 15:31 UTC, dlongley commented on test/mocha/10-meters.js
> +const database = require('bedrock-mongodb');
The above should be alphabetized by the imports:

```js
const {AbortController} = require('abort-controller');
const {createMeter, cleanDB} = require('../helpers');
const database = require('bedrock-mongodb');
const {getAppIdentity} = require('bedrock-app-identity');
const sinon = require('sinon');
```

2022-01-12 15:31 UTC, dlongley commented on test/mocha/10-meters.js
> +  it('should return "false" if "result.n" is equal to 0', async () => {
The test name shouldn't be specific to the implementation. What we're looking for here is that we get `false` when the update doesn't occur because there wasn't a match.

```suggestion
  it('should return "false" if no insert nor update occurs', async () => {
```

2022-01-12 15:31 UTC, dlongley commented on test/mocha/10-meters.js
> +    });
Hmm, I don't understand the value of this test. Can you elaborate on what we're testing here?

If we're just going to force this to be `false` -- what are we really testing? Instead, could we simulate a scenario where `false` would actually be returned and, if it does require some kind of stub, explain why in comments here?

Figuring out how to test a `false` return value will require thinking through the conditions under which it would occur and why we need to account for that situation.

2022-01-12 15:31 UTC, dlongley commented on test/mocha/10-meters.js
> +        return {data: badResponseData};
This looks good. The comment above could explain a bit more and say that this test demonstrates that the client can handle a bad response from the server, i.e., that it doesn't have to rely on the server doing the right thing.

2022-01-12 18:30 UTC, JSAssassin commented on test/mocha/10-meters.js
> +    });
I was trying to write a test to get to this line https://github.com/digitalbazaar/bedrock-meter-usage-reporter/blob/main/lib/meters.js#L150 but wasn't able to think of a scenario when it would return no document since `upsert` option is set to true here https://github.com/digitalbazaar/bedrock-meter-usage-reporter/blob/main/lib/meters.js#L143, so if I update a meter that doesn't match any of the documents in the database then it just creates a new document. Also tried updating an already existing document with the exact same data as the original data, but it also just returns the existing document.

So, I thought the only way we could get to that line was if some error or something happens when updateOne is called that results in no documents being found. That's why I stubbed the updateOne function and made it to return no docs.

Do you think it is required to return false here? https://github.com/digitalbazaar/bedrock-meter-usage-reporter/blob/main/lib/meters.js#L150. Can this be removed?

2022-01-12 18:31 UTC, JSAssassin commented on test/mocha/10-meters.js
> +const database = require('bedrock-mongodb');
Updated efd6bf1

2022-01-12 18:32 UTC, JSAssassin commented on test/mocha/10-meters.js
> +        return {data: badResponseData};
Updated a8ba899

2022-01-14 15:23 UTC, dlongley commented on test/mocha/10-meters.js
> +    });
> ...but wasn't able to think of a scenario when it would return no document since upsert option is set to true here https://github.com/digitalbazaar/bedrock-meter-usage-reporter/blob/main/lib/meters.js#L143, so if I update a meter that doesn't match any of the documents in the database then it just creates a new document...

What about the case where the query does match, but the new time wouldn't change the record? That seems to be when the code that returns `false` would happen to me. If that were to ever occur, would it be important for a caller check for `false`? If we can clearly say why it wouldn't be important, then we should remove the return value because it would be unclear then what a caller would ever do with it.

2022-01-14 15:26 UTC, dlongley commented on test/mocha/10-meters.js
> +    });
And, actually, it looks like we'd want to return the same thing we return when the record is changed (if we decide that `false` is not useful).

2022-01-14 15:38 UTC, dlongley commented on test/mocha/10-meters.js
> +    });
So, looking at this more closely, I think what we want to do is ensure that there is a matching meter record when `updateOne` returns. What's important is that we don't return `{meter: {id}}` if there is no meter record in the database.

So, ideally, we'd have a test that proves some kind of error is thrown if there's a failure to insert a meter (when there is no existing, matching record). If that checks out, then we can just always return `{meter: {id}}` from the function even if that record's `updated` time doesn't get changed -- since we're guaranteed that there is a meter record in the database (which is all we care about).

2022-01-14 15:45 UTC, dlongley commented on test/mocha/10-meters.js
> +    });
Based on the documentation for [`updateOne`](https://docs.mongodb.com/drivers/node/current/usage-examples/updateOne/), it seems like we would be ok to always return `{meter: {id}}` after `awaiting updateOne`, since it should throw if an insert (upsert) fails. It would be nice to test this, of course -- but I'm not sure if we have a simple way of triggering an insert error (I doubt it).

So, I recommend removing the conditional and always returning `{meter: {id}}` -- and if you can't figure out how to test it, that's unfortunate, but acceptable.

2022-01-14 15:47 UTC, dlongley requested changes
See comments.

2022-01-17 16:14 UTC, JSAssassin commented on test/mocha/10-meters.js
> +    });
@dlongley thanks, I've removed the conditional and made it to always return `{meter: {id}}` after the updateOne call. Wasn't sure how to test it so I've removed the test 0ec4458

2022-01-17 18:17 UTC, dlongley approved these changes

2022-01-17 18:18 UTC, merged